### ISSUE TITLE
iOS适配问题

### ISSUE THREAD

**Issue by jiandiao** [wwdc14/HyPopMenuView#1]
在iOS9下presentViewController会提示unexpected nil window in _UIApplicationHandleEventFromQueueEvent, _windowServerHitTestWindow: (null)，希望修复一下window的使用。

**Comment by wwdc14yh** [comment]
你好,我这里并没有复现你说的bug! 稍后上传我的代码你可以对比下.

**Comment by jiandiao** [comment]
好的，谢谢
