### ISSUE TITLE
导入报错

### ISSUE THREAD

**Issue by ArlenLiu** [wwdc14/HyPopMenuView#5]
导入Pop运行都没问题，一导入HyPopMenuView那六个文件就报错,编译过不了……"_OBJC_CLASS_$_POPSpringAnimation", referenced from:       objc-class-ref in HyPopMenuView.o

**Comment by wosta** [comment]
@ArlenLiu 我也遇到了这个问题，不知该如何解决@wwdc14

**Comment by wwdc14yh** [comment]
编译出错 ，确认你们pod已经集成pop库
