### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by qjsxq121** [wwdc14/HyPopMenuView#7]
菜鸟一个，已经集成了您的三方库，效果很好，但是如何添加代码当点击图标时，会跳到其它页面，而不是返回

**Comment by wwdc14yh** [comment]
你仅需要实现以下方法中的block `+(void)CreatingPopMenuObjectItmes:(NSArray<MenuLabel *> *)Items
                          TopView:(UIView *)topView
       OpenOrCloseAudioDictionary:(NSDictionary *)openOrCloseAudioDictionary
           SelectdCompletionBlock:(SelectdCompletionBlock)block`

 即可点击按钮后做你想做的事情。（这几天即将更新新版本）
